- name: install go
  ansible.builtin.dnf:
    name: go
    state: present

- name: build go application
  ansible.builtin.command: "{{item}}"
  loop:
  - go mod init dispatch
  - go get
  - go build
  args:
    chdir: /app