- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exist or not
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}
    -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'mysql'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output is: {{schema}}"

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/schema.sql"
  # when: schema.stdout != "1"

- name: "create shipping user data"
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/db/app-user.sql"

- name: "load cities data"
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/db/master-data.sql"



