- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exist or not
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}
    -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'mysql'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output is: {{schema}}"

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql"
  when: schema.stdout != "1"
