- name: install python packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - gcc
  - python36
  - python3-devel

- name: install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app 