# - name: copy catalogue service
#   ansible.builtin.copy:
#     src: catalogue.service
#     dest: /etc/systemd/system/catalogue.service

- name: "copy {{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: demon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes